name: Latest Blog Posts

on:
  schedule:
    - cron: "0 */12 * * *"   # 12시간마다 (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          # 티스토리 RSS
          feed_list: "https://suminworld.tistory.com/rss"

          # ✅ 올바른 키 이름들
          max_post_count: 5
          readme_path: "./README.md"
          commit_message: "chore(readme): update blog posts"

          # ✅ 티스토리 406/403 회피용 헤더
          user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36"
          accept_header: "application/rss+xml, application/xml;q=0.9,*/*;q=0.8"

          # 선택: 중복 제거 및 실패시 재시도
          remove_duplicates: true
          retry_count: 3
          retry_wait_time: 20
