name: Recent Activity

on:
  schedule:
    - cron: "0 */12 * * *"   # 12시간마다 (UTC 기준)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Readme-Workflows/recent-activity@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
